BMD-10462 request method fixes, Client class refactor (BC-break)
BerlingskeMedia/bpc_client pull request #16
Opened 2021-08-31 13:04 UTC by dgolabek-sii

2021-08-31 13:22 UTC, bmxpapa requested changes

2021-08-31 13:22 UTC, bmxpapa commented on lib/index.ts
> +  public url = process.env.BPC_URL || 'https://bpc.berlingskemedia.net';
let's convert this to private and setup by constructor all of public fields

2021-09-03 11:18 UTC, bmxpapa requested changes

2021-09-03 11:18 UTC, bmxpapa commented on lib/index.ts
> +  public reissueUserTicket = async (oldTicket: AppTicket): Promise<AppTicket> => this.request<AppTicket>({
```suggestion
  public getReissuedTicket = async (oldTicket: AppTicket): Promise<AppTicket> => this.request<AppTicket>({
```

2021-09-03 11:18 UTC, bmxpapa commented on lib/index.ts
> +      const result = await this.request<AppTicket>({ pathname: '/ticket/reissue', method: 'POST' }, this.appTicket);
please use getReissuedTicket here

2021-09-06 07:54 UTC, bmxpiku approved these changes

2021-09-08 10:13 UTC, bmxpapa approved these changes

2021-09-16 09:23 UTC, merged